### PR TITLE
audiovideo => tessel-av

### PR DESCRIPTION
**Pull request by rwaldron**

### CODE REVIEW

**Comment by johnnyman727** [comment]
looks good to me.

**Comment by Frijol** [comment]
needs to be updated on tessel.io/modules too

**Comment by johnnyman727** [comment]
@Frijol I believe tessel.io/modules pull from this JSON file. If you go to that website you'll see it's already updated.

**Comment by Frijol** [comment]
oh right, I forgot I did that! We're so clever.

**Pull request merged**
